---
- name: Create Groups
  hosts: localhost
  vars:
    dev_group: 'DevGroup2'
  gather_facts: False
  connection: local
  tasks:
    - name: Create dev Server Group
      clc_group:
        name: "{{ dev_group }}"
        parent: 'GavinTest'
        location: CA2
        state: present
      register: clc
- name: Build Servers
  hosts: localhost
  vars:
    dev_group: 'DevGroup2'
  gather_facts: false
  connection: local
  tasks:
    - name: Build linux Servers
      clc_server:
        cpu: 1
        memory: 1
        description: 'Runner Ubuntu Server'
        location: CA2
        group: "{{ dev_group }}"
        managed_os: false
        name: test
        network_id: 606822678a2a4957bae5e46e7ca1bc75
        template: UBUNTU-14-64-TEMPLATE
        count: 1
      register: clc
